# Generated by Django 4.1 on 2022-09-02 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('capacidade', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
